In [1]:
import numpy as np

In [2]:
a = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [4]:
a.shape

(2, 2, 4)

In [5]:
a[:,:,0]

array([[ 1,  5],
       [ 9, 13]])

In [6]:
a[0,:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
a[:,0,:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])